# we want to source the global bash profile, since it defines usefull
source /etc/profile

typeset -U path
# export ANDROID_HOME=$HOME/Android/Sdk
addpaths=("$HOME/bin" "$HOME/.local/bin")

for p in $addpaths; do
if [[ -d "$p" ]]; then
    path=("$p" $path[@])
fi
done
