
# we want to source the global bash profile, since it defines useful
# emulate sh -c 'source /etc/profile'

typeset -U path
addpaths=("$HOME/bin" "$HOME/.local/bin" "/Applications/kitty.app/Contents/MacOS")

for p in $addpaths; do
if [[ -d "$p" ]]; then
  path=("$p" $path[@])
fi
done

if [[ -d "$HOME/.local/opt" ]]; then
  for p in "$HOME/.local/opt/"*; do
    if [[ -d "$p/bin" ]]; then
      path=("$p/bin" $path[@])
    fi
  done
fi
