# Fig pre block. Keep at the top of this file.
export PATH="${PATH}:${HOME}/.local/bin"
eval "$(fig init zsh pre)"

# we want to source the global bash profile, since it defines useful
# emulate sh -c 'source /etc/profile'

typeset -U path
addpaths=("$HOME/bin" "$HOME/.local/bin" "/Applications/kitty.app/Contents/MacOS")

for p in $addpaths; do
if [[ -d "$p" ]]; then
  path=("$p" $path[@])
fi
done

# Fig post block. Keep at the bottom of this file.
eval "$(fig init zsh post)"
