export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export EDITOR=vim
export NVM_DIR="$HOME/.nvm"
export QT_QPA_PLATFORMTHEME="qt5ct"
export ELECTRON_TRASH="gio"
export R_LIBS_USER="$HOME/.local/share/R/library"
